# This GitHub action runs your tests for each commit push and/or PR.
#
name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
    # Allows us to trigger this action manually.
env:
  GOEXPERIMENT: boringcrypto

jobs:
  build-and-test:
    name: Build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ 1.21, 1.22 ]
        # Use a dynamic matrix to allow testing multiple OSes and Go versions
        # in the public repository but reduce combinations in private clones.
        exclude:
          - os: ${{ github.repository_owner == 'clumio-code' && '_' || 'macos-latest' }}
          - os: ${{ github.repository_owner == 'clumio-code' && '_' || 'windows-latest' }}
          - go: ${{ github.repository_owner == 'sodul' && '_' || '1.22' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Show Environment
      run: |
        echo "matrix.os=${{ matrix.os }}"
        echo "matrix.go=${{ matrix.go }}"
        echo "github.repository_owner=${{ github.repository_owner }}"
        go version

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: |
        go build -v .

    - name: TF unit tests
      timeout-minutes: 5
      shell: bash
      run: |
        for TF in '1.4.*' '1.5.*' '1.6.*' '1.7.*'; do
        TF_ACC_TERRAFORM_VERSION=$TF go test -v -cover ./clumio/plugin_framework;
        done
